/* ============================================================
   Building Compliance Checker – app.js
   Vanilla JS, no dependencies except jsPDF (loaded on demand)
   ============================================================ */

'use strict';

// ---- i18n strings -------------------------------------------------------
const STRINGS = {
  en: {
    appTitle:             'Building Compliance Checker',
    heroTitle:            'Building Compliance Checker',
    heroSubtitle:         'Select a project type and region to view all applicable requirements.',
    labelProjectType:     'Project Type',
    labelRegion:          'Region',
    placeholderProjectType: 'Select Project Type',
    placeholderRegion:    'Select Region',
    modeReview:           'Review Mode',
    modeGap:              'Gap Mode',
    progressOf:           ' of ',
    progressLabel:        ' requirements met',
    exportBtn:            'Export Report',
    staleNotice:          'Some requirements have not been verified in over 12 months. Please check the source before relying on these.',
    emptyStateText:       'Select a project type and region above to view compliance requirements.',
    footerDisclaimer:     'This tool is for reference only. Always verify requirements with official sources before making project decisions.',
    footerLegal:          'Legal content shown in German only. Translation of legal text introduces risk of misinterpretation.',
    colMet:               'Met',
    colUnmet:             'Not Met',
    badgeFunding:         'Funding relevant',
    badgeLocal:           'Local verification required',
    lastVerified:         'Last verified:',
    staleWarning:         'Verify – over 12 months old',
    pdfTitle:             'Compliance Report',
    pdfProjectType:       'Project Type:',
    pdfRegion:            'Region:',
    pdfDate:              'Date of Review:',
    pdfMetSection:        'MET REQUIREMENTS',
    pdfUnmetSection:      'UNMET / UNCHECKED REQUIREMENTS',
    pdfSummary:           'SUMMARY',
    pdfProgress:          'Requirements met:',
    pdfFooter:            'Generated by Building Compliance Checker. For reference only.',
    'Planning & Zoning':     'Planning & Zoning',
    'Building Code':         'Building Code',
    'Fire Safety':           'Fire Safety',
    'Accessibility':         'Accessibility',
    'Energy & Sustainability': 'Energy & Sustainability',
    'Room Standards':        'Room Standards',
    'Proximity Restrictions': 'Proximity Restrictions',
    'Staffing & Operations': 'Staffing & Operations',
    'Funding Eligibility':   'Funding Eligibility',
    'Permits & Approvals':   'Permits & Approvals',
    // Group headers
    group_residential:    'Residential',
    group_commercial:     'Commercial',
    group_care_social:    'Care & Social',
    group_industrial:     'Industrial',
    group_public:         'Public / Infrastructure',
    // Type labels
    single_family_home:   'Single Family Home',
    multi_family_home:    'Multi Family Home',
    residential:          'Apartment Building',
    student_housing:      'Student Housing',
    social_housing:       'Social Housing',
    office_building:      'Office Building',
    retail:               'Retail / Shop',
    hotel:                'Hotel',
    restaurant:           'Restaurant / Food Service',
    mixed_use:            'Mixed Use – Residential + Commercial',
    retirement_home:      'Retirement Home',
    assisted_living:      'Assisted Living',
    disability_care:      'Disability Care Facility',
    childrens_home:       "Children's Home",
    kindergarten:         'Kindergarten / Daycare',
    warehouse:            'Warehouse / Logistics',
    light_industrial:     'Light Industrial / Workshop',
    factory:              'Factory',
    school:               'School',
    hospital:             'Hospital',
    sports_facility:      'Sports Facility',
    community_centre:     'Community Centre',
    place_of_worship:     'Place of Worship',
    projectsTitle:        'Saved Projects',
    projectsEmpty:        'No saved projects yet.',
    saveProjectLabel:     'Save current state as:',
    projectNamePlaceholder: 'Project name…',
    saveProjectBtn:       'Save',
    deleteProjectBtn:     'Delete selected',
    msgSaved:             'Project saved.',
    msgUpdated:           'Project updated.',
    msgDeleted:           'Project deleted.',
    msgNoName:            'Please enter a project name.',
    msgNoSelection:       'Please select a project type and region first.',
  },
  de: {
    appTitle:             'Baurechts-Compliance-Checker',
    heroTitle:            'Baurechts-Compliance-Checker',
    heroSubtitle:         'Wählen Sie einen Projekttyp und eine Region, um alle geltenden Anforderungen anzuzeigen.',
    labelProjectType:     'Projekttyp',
    labelRegion:          'Region',
    placeholderProjectType: 'Projekttyp auswählen',
    placeholderRegion:    'Region auswählen',
    modeReview:           'Überprüfungsmodus',
    modeGap:              'Lückenmodus',
    progressOf:           ' von ',
    progressLabel:        ' Anforderungen erfüllt',
    exportBtn:            'Bericht exportieren',
    staleNotice:          'Einige Anforderungen wurden seit über 12 Monaten nicht mehr verifiziert. Bitte prüfen Sie die Quelle, bevor Sie sich darauf verlassen.',
    emptyStateText:       'Wählen Sie oben einen Projekttyp und eine Region aus, um die Compliance-Anforderungen anzuzeigen.',
    footerDisclaimer:     'Dieses Tool dient nur zur Orientierung. Bitte verifizieren Sie Anforderungen immer mit offiziellen Quellen, bevor Sie Projektentscheidungen treffen.',
    footerLegal:          'Rechtliche Inhalte werden ausschließlich auf Deutsch angezeigt. Die Übersetzung von Gesetzestexten birgt das Risiko von Fehlinterpretationen.',
    colMet:               'Erfüllt',
    colUnmet:             'Nicht erfüllt',
    badgeFunding:         'Förderrelevant',
    badgeLocal:           'Lokale Prüfung erforderlich',
    lastVerified:         'Zuletzt geprüft:',
    staleWarning:         'Prüfen – über 12 Monate alt',
    pdfTitle:             'Compliance-Bericht',
    pdfProjectType:       'Projekttyp:',
    pdfRegion:            'Region:',
    pdfDate:              'Prüfdatum:',
    pdfMetSection:        'ERFÜLLTE ANFORDERUNGEN',
    pdfUnmetSection:      'NICHT ERFÜLLTE / UNGEPRÜFTE ANFORDERUNGEN',
    pdfSummary:           'ZUSAMMENFASSUNG',
    pdfProgress:          'Anforderungen erfüllt:',
    pdfFooter:            'Erstellt mit dem Baurechts-Compliance-Checker. Nur zur Orientierung.',
    'Planning & Zoning':     'Planung & Bebauung',
    'Building Code':         'Bauordnungsrecht',
    'Fire Safety':           'Brandschutz',
    'Accessibility':         'Barrierefreiheit',
    'Energy & Sustainability': 'Energie & Nachhaltigkeit',
    'Room Standards':        'Raumstandards',
    'Proximity Restrictions': 'Näherungs- und Abstandsregelungen',
    'Staffing & Operations': 'Personal & Betrieb',
    'Funding Eligibility':   'Fördervoraussetzungen',
    'Permits & Approvals':   'Genehmigungen & Zulassungen',
    // Group headers
    group_residential:    'Wohnen',
    group_commercial:     'Gewerbe',
    group_care_social:    'Pflege & Soziales',
    group_industrial:     'Industrie',
    group_public:         'Öffentlich / Infrastruktur',
    // Type labels
    single_family_home:   'Einfamilienhaus',
    multi_family_home:    'Mehrfamilienhaus',
    residential:          'Wohngebäude',
    student_housing:      'Studentenwohnheim',
    social_housing:       'Sozialwohnungen',
    office_building:      'Bürogebäude',
    retail:               'Einzelhandel',
    hotel:                'Hotel',
    restaurant:           'Gastronomie',
    mixed_use:            'Mischnutzung (Wohnen + Gewerbe)',
    retirement_home:      'Pflegeheim / Altenheim',
    assisted_living:      'Betreutes Wohnen',
    disability_care:      'Behinderteneinrichtung',
    childrens_home:       'Kinderheim',
    kindergarten:         'Kindertagesstätte',
    warehouse:            'Lager / Logistik',
    light_industrial:     'Leichtindustrie / Werkstatt',
    factory:              'Fabrik / Produktionsanlage',
    school:               'Schule',
    hospital:             'Krankenhaus',
    sports_facility:      'Sportstätte',
    community_centre:     'Gemeinschaftseinrichtung',
    place_of_worship:     'Gotteshaus',
    projectsTitle:        'Gespeicherte Projekte',
    projectsEmpty:        'Noch keine gespeicherten Projekte.',
    saveProjectLabel:     'Aktuellen Stand speichern als:',
    projectNamePlaceholder: 'Projektname…',
    saveProjectBtn:       'Speichern',
    deleteProjectBtn:     'Auswahl löschen',
    msgSaved:             'Projekt gespeichert.',
    msgUpdated:           'Projekt aktualisiert.',
    msgDeleted:           'Projekt gelöscht.',
    msgNoName:            'Bitte einen Projektnamen eingeben.',
    msgNoSelection:       'Bitte zuerst Projekttyp und Region auswählen.',
  }
};

const CATEGORY_ORDER = [
  'Planning & Zoning', 'Building Code', 'Fire Safety', 'Accessibility',
  'Energy & Sustainability', 'Room Standards', 'Proximity Restrictions',
  'Staffing & Operations', 'Funding Eligibility', 'Permits & Approvals'
];

// Grouped dropdown structure — add new types here as data is added
const BUILDING_GROUPS = [
  { key: 'group_residential', types: [
    'single_family_home', 'multi_family_home', 'residential',
    'student_housing', 'social_housing',
  ]},
  { key: 'group_commercial', types: [
    'office_building', 'retail', 'hotel', 'restaurant', 'mixed_use',
  ]},
  { key: 'group_care_social', types: [
    'retirement_home', 'assisted_living', 'disability_care',
    'childrens_home', 'kindergarten',
  ]},
  { key: 'group_industrial', types: [
    'warehouse', 'light_industrial', 'factory',
  ]},
  { key: 'group_public', types: [
    'school', 'hospital', 'sports_facility', 'community_centre', 'place_of_worship',
  ]},
];

// ---- Category icon SVG path data ----------------------------------------
const CAT_ICONS = {
  'Planning & Zoning':      { cls: 'cat-icon-planning',  d: 'M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7' },
  'Building Code':          { cls: 'cat-icon-building',  d: 'M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z' },
  'Fire Safety':            { cls: 'cat-icon-fire',      d: 'M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7C14 5 16.09 5.777 17.656 7.343A7.975 7.975 0 0120 13a7.975 7.975 0 01-2.343 5.657z' },
  'Accessibility':          { cls: 'cat-icon-access',    d: 'M12 2a2 2 0 100 4 2 2 0 000-4zm-1 7l-3 9h2l1-3h2l1 3h2l-3-9h-2z' },
  'Energy & Sustainability':{ cls: 'cat-icon-energy',    d: 'M13 10V3L4 14h7v7l9-11h-7z' },
  'Room Standards':         { cls: 'cat-icon-room',      d: 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6' },
  'Proximity Restrictions': { cls: 'cat-icon-proximity', d: 'M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z M15 11a3 3 0 11-6 0 3 3 0 016 0z' },
  'Staffing & Operations':  { cls: 'cat-icon-staffing',  d: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z' },
  'Funding Eligibility':    { cls: 'cat-icon-funding',   d: 'M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z' },
  'Permits & Approvals':    { cls: 'cat-icon-permits',   d: 'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z' },
};

// ---- State ---------------------------------------------------------------
let complianceData   = null;
let currentReqs      = [];   // flat array of requirements for current selection
let checkedIds       = new Set();
let currentLang      = 'en';
let currentMode      = 'review';

// ---- Boot ----------------------------------------------------------------
document.addEventListener('DOMContentLoaded', async () => {
  await loadData();
  populateDropdowns();
  bindEvents();
  applyLang();
});

async function loadData() {
  complianceData = window.COMPLIANCE_DATA;
}

// ---- Populate dropdowns --------------------------------------------------
function populateDropdowns() {
  const projectSel = document.getElementById('projectType');
  const regionSel  = document.getElementById('region');

  // Regions: dynamic from JSON
  Object.keys(complianceData.regions).forEach(rKey => {
    const opt = document.createElement('option');
    opt.value = rKey;
    opt.textContent = complianceData.regions[rKey].name || rKey;
    regionSel.appendChild(opt);
  });

  // Collect which type keys actually have data (any region)
  const availableTypes = new Set();
  Object.values(complianceData.regions).forEach(region => {
    Object.keys(region).filter(k => k !== 'name').forEach(k => availableTypes.add(k));
  });

  // Build grouped optgroups from BUILDING_GROUPS structure
  BUILDING_GROUPS.forEach(group => {
    const optgroup = document.createElement('optgroup');
    optgroup.dataset.groupKey = group.key;
    optgroup.label = t(group.key);
    group.types.forEach(typeKey => {
      const opt = document.createElement('option');
      opt.value = typeKey;
      opt.dataset.projectType = typeKey;
      opt.textContent = t(typeKey);
      if (!availableTypes.has(typeKey)) opt.disabled = true;
      optgroup.appendChild(opt);
    });
    projectSel.appendChild(optgroup);
  });
}

// ---- i18n ----------------------------------------------------------------
function t(key) {
  return (STRINGS[currentLang] || STRINGS.en)[key] || key;
}

function applyLang() {
  // Static UI strings
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (el.tagName === 'OPTION') return;
    el.textContent = t(key);
  });
  // Placeholder <option> in selects
  document.querySelectorAll('select option[data-i18n]').forEach(opt => {
    opt.textContent = t(opt.dataset.i18n);
  });
  // Optgroup labels and option text in project type select
  document.querySelectorAll('#projectType optgroup[data-group-key]').forEach(og => {
    og.label = t(og.dataset.groupKey);
  });
  document.querySelectorAll('option[data-project-type]').forEach(opt => {
    opt.textContent = t(opt.dataset.projectType) || opt.dataset.projectType;
  });
  // Placeholder attributes
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.dataset.i18nPlaceholder);
  });
  document.getElementById('langLabel').textContent = currentLang === 'en' ? 'DE' : 'EN';
  document.documentElement.lang = currentLang;

  // Re-render results if visible
  if (currentReqs.length > 0) renderResults();
}

// ---- Events --------------------------------------------------------------
function bindEvents() {
  document.getElementById('projectType').addEventListener('change', onSelectionChange);
  document.getElementById('region').addEventListener('change', onSelectionChange);
  document.getElementById('langToggle').addEventListener('click', () => {
    currentLang = currentLang === 'en' ? 'de' : 'en';
    applyLang();
  });
  document.getElementById('btnReview').addEventListener('click', () => setMode('review'));
  document.getElementById('btnGap').addEventListener('click', () => setMode('gap'));
  document.getElementById('exportBtn').addEventListener('click', exportPDF);
  // Projects sidebar
  document.getElementById('projectsSelect').addEventListener('change', onProjectSelect);
  document.getElementById('saveProjectBtn').addEventListener('click', onSaveProject);
  document.getElementById('deleteProjectBtn').addEventListener('click', onDeleteProject);
  renderProjectList();
}

function onSelectionChange() {
  const projectType = document.getElementById('projectType').value;
  const region      = document.getElementById('region').value;
  if (!projectType || !region) {
    currentReqs = [];
    document.getElementById('resultsArea').hidden = true;
    document.getElementById('emptyState').hidden  = false;
    return;
  }
  const regionData = complianceData.regions[region];
  currentReqs = (regionData && regionData[projectType]) ? regionData[projectType] : [];
  checkedIds.clear();
  document.getElementById('resultsArea').hidden = false;
  document.getElementById('emptyState').hidden  = true;
  renderResults();
}

function setMode(mode) {
  currentMode = mode;
  document.body.classList.toggle('gap-mode', mode === 'gap');
  document.getElementById('btnReview').classList.toggle('active', mode === 'review');
  document.getElementById('btnGap').classList.toggle('active', mode === 'gap');
}

// ---- Render all categories ----------------------------------------------
function renderResults() {
  const container = document.getElementById('categoriesContainer');
  // Remember which categories are collapsed
  const collapsedCats = new Set();
  container.querySelectorAll('.category-section.collapsed').forEach(s => {
    collapsedCats.add(s.dataset.category);
  });
  container.innerHTML = '';

  // Group by category
  const grouped = {};
  currentReqs.forEach(req => {
    if (!grouped[req.category]) grouped[req.category] = [];
    grouped[req.category].push(req);
  });

  // Stale check (> 12 months)
  const cutoff = new Date();
  cutoff.setFullYear(cutoff.getFullYear() - 1);
  const hasStale = currentReqs.some(r => new Date(r.last_verified) < cutoff);
  document.getElementById('staleNotice').hidden = !hasStale;

  CATEGORY_ORDER
    .filter(cat => grouped[cat])
    .forEach(cat => {
      const section = buildCategorySection(cat, grouped[cat]);
      if (collapsedCats.has(cat)) section.classList.add('collapsed');
      container.appendChild(section);
    });

  updateProgress();
}

// ---- Build one category section -----------------------------------------
function buildCategorySection(category, reqs) {
  const section = document.createElement('div');
  section.className = 'category-section';
  section.dataset.category = category;

  const icon = CAT_ICONS[category] || { cls: '', d: 'M12 6v6m0 0v6m0-6h6m-6 0H6' };

  // Header
  const header = document.createElement('div');
  header.className = 'category-header';
  header.innerHTML = `
    <svg class="category-icon ${icon.cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="${icon.d}"/>
    </svg>
    <span class="category-title">${t(category)}</span>
    <span class="category-count">${reqs.length}</span>
    <svg class="category-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7"/>
    </svg>
  `;
  header.addEventListener('click', () => section.classList.toggle('collapsed'));

  // Body
  const body = document.createElement('div');
  body.className = 'category-body';

  // Two-column wrapper (review mode); single column in gap mode via CSS
  const columns = document.createElement('div');
  columns.className = 'review-columns';

  const metCol   = document.createElement('div');
  metCol.className = 'review-col';

  const unmetCol = document.createElement('div');
  unmetCol.className = 'review-col';

  const metHeader = document.createElement('div');
  metHeader.className = 'review-column-header met';
  metHeader.textContent = t('colMet');

  const unmetHeader = document.createElement('div');
  unmetHeader.className = 'review-column-header unmet';
  unmetHeader.textContent = t('colUnmet');

  const metList   = document.createElement('ul');
  metList.className = 'requirements-list met-list';

  const unmetList = document.createElement('ul');
  unmetList.className = 'requirements-list unmet-list';

  reqs.forEach(req => {
    const item = buildReqItem(req);
    if (checkedIds.has(req.id)) metList.appendChild(item);
    else unmetList.appendChild(item);
  });

  metCol.appendChild(metHeader);
  metCol.appendChild(metList);
  unmetCol.appendChild(unmetHeader);
  unmetCol.appendChild(unmetList);
  columns.appendChild(metCol);
  columns.appendChild(unmetCol);
  body.appendChild(columns);
  section.appendChild(header);
  section.appendChild(body);
  return section;
}

// ---- Build one requirement item -----------------------------------------
function buildReqItem(req) {
  const cutoff = new Date();
  cutoff.setFullYear(cutoff.getFullYear() - 1);
  const isStale = new Date(req.last_verified) < cutoff;
  const isMet   = checkedIds.has(req.id);
  const isLocal = typeof req.detail === 'string' &&
    (req.detail.includes('lokale') || req.detail.includes('Gemeinde') ||
     req.detail.includes('kommunal') || req.detail.includes('Bebauungsplan'));

  const li = document.createElement('li');
  li.className = 'req-item' + (isMet ? ' is-met' : '') + (isStale ? ' is-stale' : '');
  li.dataset.reqId = req.id;

  const staleIcon = isStale
    ? `<span class="req-stale-icon" title="${t('staleWarning')}">
         <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
           <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>
           <line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
         </svg>
       </span>`
    : '';

  const staleMeta = isStale
    ? `<span class="req-stale">${t('staleWarning')}</span>`
    : '';

  const localBadge   = isLocal  ? `<span class="req-badge-local">${t('badgeLocal')}</span>` : '';
  const fundingBadge = req.applies_to_funding ? `<span class="req-badge-funding">${t('badgeFunding')}</span>` : '';

  li.innerHTML = `
    <input type="checkbox" class="req-checkbox" ${isMet ? 'checked' : ''}
      data-req-id="${req.id}" aria-label="${req.id}">
    <div class="req-body">
      <div class="req-title">${staleIcon}${escapeHtml(req.requirement)}</div>
      <div class="req-detail">${escapeHtml(req.detail)}</div>
      <div class="req-meta">
        <a class="req-source" href="${escapeAttr(req.source_url)}" target="_blank" rel="noopener noreferrer">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/>
          </svg>
          ${escapeHtml(req.source_law)}
        </a>
        <span class="req-verified">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <rect x="3" y="4" width="18" height="18" rx="2"/>
            <line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/>
            <line x1="3" y1="10" x2="21" y2="10"/>
          </svg>
          ${t('lastVerified')} ${escapeHtml(req.last_verified)}
        </span>
        ${staleMeta}${fundingBadge}${localBadge}
      </div>
    </div>
  `;

  // Checkbox: move item between met/unmet columns without full re-render
  li.querySelector('.req-checkbox').addEventListener('change', e => {
    const id = e.target.dataset.reqId;
    if (e.target.checked) {
      checkedIds.add(id);
      li.classList.add('is-met');
      // Move to met list
      const section = li.closest('.category-section');
      if (section) section.querySelector('.met-list').appendChild(li);
    } else {
      checkedIds.delete(id);
      li.classList.remove('is-met');
      // Move to unmet list
      const section = li.closest('.category-section');
      if (section) section.querySelector('.unmet-list').appendChild(li);
    }
    updateProgress();
  });

  return li;
}

// ---- Progress indicator -------------------------------------------------
function updateProgress() {
  const total = currentReqs.length;
  const met   = checkedIds.size;
  const pct   = total > 0 ? (met / total) * 100 : 0;

  document.getElementById('progressCount').textContent = met;
  document.getElementById('progressTotal').textContent  = total;

  const bar = document.getElementById('progressBar');
  bar.style.width = pct + '%';
  bar.className = 'progress-bar' + (pct >= 80 ? ' green' : pct >= 40 ? ' amber' : '');
}

// ---- PDF Export ---------------------------------------------------------
async function exportPDF() {
  if (!window.jspdf) {
    await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');
  }
  const { jsPDF } = window.jspdf;

  const projectType = document.getElementById('projectType').value;
  const region      = document.getElementById('region').value;
  const projectName = t(projectType) || projectType;
  const regionName  = complianceData.regions[region]?.name || region;
  const dateStr     = new Date().toISOString().split('T')[0];

  const met   = currentReqs.filter(r =>  checkedIds.has(r.id));
  const unmet = currentReqs.filter(r => !checkedIds.has(r.id));

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const PAGE_H = 297;
  const MARGIN = 15;
  const TW     = 210 - MARGIN * 2;
  let y = 20;

  const checkPage = (needed = 12) => {
    if (y + needed > PAGE_H - 20) { doc.addPage(); y = 20; }
  };

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(13, 110, 253);
  doc.text(t('pdfTitle'), MARGIN, y);
  y += 10;

  // Meta
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`${t('pdfProjectType')} ${projectName}`, MARGIN, y); y += 6;
  doc.text(`${t('pdfRegion')} ${regionName}`, MARGIN, y);       y += 6;
  doc.text(`${t('pdfDate')} ${dateStr}`, MARGIN, y);            y += 8;

  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y, 210 - MARGIN, y);
  y += 8;

  // Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(33, 37, 41);
  doc.text(t('pdfSummary'), MARGIN, y); y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${t('pdfProgress')} ${met.length} / ${currentReqs.length}`, MARGIN, y);
  y += 10;

  const addReqBlock = (req, isMet) => {
    checkPage(30);
    const [r, g, b] = isMet ? [209, 231, 221] : [248, 215, 218];
    doc.setFillColor(r, g, b);
    doc.rect(MARGIN, y, 3, 5, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(33, 37, 41);
    const titleLines = doc.splitTextToSize(req.requirement, TW - 6);
    doc.text(titleLines, MARGIN + 6, y + 4);
    y += Math.max(titleLines.length * 5, 8);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    const detailLines = doc.splitTextToSize(req.detail, TW - 6);
    checkPage(detailLines.length * 4 + 8);
    doc.text(detailLines, MARGIN + 6, y);
    y += detailLines.length * 4 + 3;

    doc.setFontSize(7.5);
    doc.setTextColor(13, 110, 253);
    doc.text(`${req.source_law}  |  ${t('lastVerified')} ${req.last_verified}`, MARGIN + 6, y);
    y += 7;
  };

  if (met.length > 0) {
    checkPage(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(25, 135, 84);
    doc.text(t('pdfMetSection'), MARGIN, y); y += 8;
    met.forEach(r => addReqBlock(r, true));
    y += 4;
  }

  if (unmet.length > 0) {
    checkPage(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(220, 53, 69);
    doc.text(t('pdfUnmetSection'), MARGIN, y); y += 8;
    unmet.forEach(r => addReqBlock(r, false));
  }

  // Footer on each page
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(t('pdfFooter'), MARGIN, PAGE_H - 7);
    doc.text(`${i} / ${pages}`, 210 - MARGIN, PAGE_H - 7, { align: 'right' });
  }

  doc.save(`compliance-${region}-${projectType}-${dateStr}.pdf`);
}

function loadScript(src) {
  return new Promise((res, rej) => {
    const s = document.createElement('script');
    s.src = src; s.onload = res; s.onerror = rej;
    document.head.appendChild(s);
  });
}

// ---- Helpers -------------------------------------------------------------
function escapeHtml(str) {
  if (typeof str !== 'string') return '';
  return str.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
function escapeAttr(str) {
  if (typeof str !== 'string') return '#';
  // Allow only http(s) URLs
  if (!/^https?:\/\//i.test(str)) return '#';
  return str.replace(/"/g, '%22');
}

// ---- Project persistence (localStorage) ---------------------------------
const STORAGE_KEY = 'bcc_projects';

function loadProjects() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
  } catch { return []; }
}

function saveProjects(projects) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(projects));
}

function renderProjectList() {
  const sel      = document.getElementById('projectsSelect');
  const emptyMsg = document.getElementById('projectsEmptyMsg');
  const delBtn   = document.getElementById('deleteProjectBtn');
  const projects = loadProjects();

  // Keep currently selected id if still valid
  const prevId = sel.value;
  sel.innerHTML = '';

  if (projects.length === 0) {
    sel.hidden    = true;
    emptyMsg.hidden = false;
    delBtn.disabled = true;
    return;
  }

  sel.hidden      = false;
  emptyMsg.hidden = true;

  projects.forEach(p => {
    const opt = document.createElement('option');
    opt.value = p.id;
    opt.textContent = p.name;
    if (p.id === prevId) opt.selected = true;
    sel.appendChild(opt);
  });

  delBtn.disabled = !sel.value;
}

function onProjectSelect() {
  const sel      = document.getElementById('projectsSelect');
  const delBtn   = document.getElementById('deleteProjectBtn');
  delBtn.disabled = !sel.value;

  const id       = sel.value;
  if (!id) return;
  const projects = loadProjects();
  const project  = projects.find(p => p.id === id);
  if (!project) return;

  // Restore dropdowns
  document.getElementById('region').value      = project.region;
  document.getElementById('projectType').value = project.projectType;

  // Restore requirements list
  const regionData = complianceData.regions[project.region];
  currentReqs      = (regionData && regionData[project.projectType]) ? regionData[project.projectType] : [];
  checkedIds       = new Set(project.checkedIds);

  document.getElementById('resultsArea').hidden = false;
  document.getElementById('emptyState').hidden  = true;
  renderResults();
}

function onSaveProject() {
  const name  = document.getElementById('projectNameInput').value.trim();
  const type  = document.getElementById('projectType').value;
  const region = document.getElementById('region').value;

  if (!name) {
    showPanelMsg(t('msgNoName'), 'err');
    return;
  }
  if (!type || !region) {
    showPanelMsg(t('msgNoSelection'), 'err');
    return;
  }

  const projects  = loadProjects();
  const existing  = projects.find(p => p.name === name);
  let msgKey;

  if (existing) {
    // Overwrite in place
    existing.region      = region;
    existing.projectType = type;
    existing.checkedIds  = [...checkedIds];
    existing.savedAt     = new Date().toISOString();
    msgKey = 'msgUpdated';
  } else {
    projects.push({
      id:          Date.now().toString(),
      name,
      region,
      projectType: type,
      checkedIds:  [...checkedIds],
      savedAt:     new Date().toISOString(),
    });
    msgKey = 'msgSaved';
  }

  saveProjects(projects);
  document.getElementById('projectNameInput').value = '';
  renderProjectList();
  // Select the just-saved project in the list
  const sel = document.getElementById('projectsSelect');
  const target = existing || projects[projects.length - 1];
  sel.value = target.id;
  document.getElementById('deleteProjectBtn').disabled = false;
  showPanelMsg(t(msgKey), 'ok');
}

function onDeleteProject() {
  const sel = document.getElementById('projectsSelect');
  const id  = sel.value;
  if (!id) return;
  const projects  = loadProjects().filter(p => p.id !== id);
  saveProjects(projects);
  renderProjectList();
  showPanelMsg(t('msgDeleted'), 'ok');
}

function showPanelMsg(text, type) {
  const el = document.getElementById('panelMsg');
  el.textContent = text;
  el.className   = 'panel-msg ' + type;
  el.hidden      = false;
  clearTimeout(el._timer);
  el._timer = setTimeout(() => { el.hidden = true; }, 3000);
}
